### ISSUE TITLE
Parser does not handle block-all-mixed-content and report-uri directives correctly

### ISSUE THREAD

**Issue by nudge** [helmetjs/content-security-policy-parser#1]
Parsing a CSP string containing `block-all-mixed-content` returns `block-all-mixed-content: []` which fails to load into `helmet/csp` as it should be `true` or `false`, not an array.

Parsing a CSP string  containing `report-uri` returns `report-uri: ['url']` which fails to load into `helmet/csp` as it requires a string, not an array.

**Comment by EvanHahn** [comment]
This module is used in `helmet/csp`'s testing and should really be called something like `policy-parser`. Its return values are deliberately consistent (arrays).

But you're kinda right—this doesn't really parse content security policies.

Are you interested in using this module for that purpose?

**Comment by nudge** [comment]
Thanks for the response Evan. I was thinking of using it to parse an existing `csp`string into a directives object in order to modify it, then set the directives again.

**Comment by nudge** [comment]
If i get some down time i'll have a crack at it. Cheers!

**Comment by EvanHahn** [comment]
Cool! I wouldn't expect that to be part of this module, just FYI.

**Comment by EvanHahn** [comment]
I believe this issue is mostly solved so I'm going to close it. Lemme know if that's wrong or if I can help further!
